version: '3'

services:
  postgres:
    image: 'postgres:12'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=CraftGruz'
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: "pgadmin"
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@adminEmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=root'
    ports:
      - 5000:80

  app:
    build: ./
    container_name: 'java-load'
    depends_on:
      - postgres
    ports:
      - 8089:8088